server:
  port: 8082
spring:
  mail:
    host: smtp.163.com
    protocol: smtp
    default-encoding: UTF-8
    password: SAWPUTZLSZECIEWA
    username: hc894392782@163.com
    port: 25

  rabbitmq:
    username: guest
    password: guest
    host: 192.168.181.128
    port: 5672
    listener:
      simple:
        acknowledge-mode: manual
  redis:
    timeout: 10000ms
    host: 192.168.181.128
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 1024
        max-wait: 10000ms
        #最大空闲链接
        max-idle: 200
        min-idle: 5
